#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments



#export CUDA_ROOT=/usr/local/cuda
#export CUDA_HEADERS=${CUDA_ROOT:-/usr/local/cuda}/include
#export CUDA_LIBS=${CUDA_ROOT:-/usr/local/cuda}/lib64

export CUDA_ROOT=$NVHPC_ROOT/cuda
export CUDA_HEADERS=$CUDA_ROOT/include
export CUDA_LIBS=$CUDA_ROOT/lib64

wmakeLnInclude src
wmake src/gpuKernelEvaluator
wmake src/gpuChemistryModels
wmake catchMain
wmake unittest
#wmake benchmark

# ----------------------------------------------------------------- end-of-file
