#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments


wmakeLnInclude src
wmake src/gpuKernelEvaluator
wmake src/gpuChemistryModels
wmake catchMain
wmake unittest/testHelpers
wmake unittest/cpuResults
wmake unittest/gpuResults
wmake unittest/tests
#wmake all unittest
#wmake all benchmark

# ----------------------------------------------------------------- end-of-file
