#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


wclean all src
wclean all unittest
wclean all benchmark
wclean all profile

# ----------------------------------------------------------------- end-of-file
