#!/bin/bash

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NSTEPS=2000

for ODE in "Rosenbrock23" "Rosenbrock34"
do
    for MECH in "gri" "yao" "h2"
    do
        for MODEL in "gpu" "cpu"
        do
            for CORES in 1 10 20 40 80
            do
                BASE=$MECH
                CASE="$MODEL-$MECH-$ODE-$CORES"
                cp -r $BASE $CASE
                cd $CASE
                ./Allrun $MODEL $CORES $NSTEPS $ODE
                cd ..
            done
        done
    done
done
#------------------------------------------------------------------------------

